# Generated by Django 4.2.11 on 2024-06-21 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_filmwork_rating_genrefilmwork_filmwork_genres"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=512, verbose_name="Полное имя"),
                ),
            ],
            options={"db_table": 'content"."person',},
        ),
    ]
