# Generated by Django 4.2.11 on 2024-07-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_alter_genre_description"),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS film_work_creation_date_idx ON content.film_work(creation_date);',
            reverse_sql='DROP INDEX film_work_creation_date_idx;',
        ),
        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX IF NOT EXISTS film_work_person_idx ON content.person_film_work 
            (film_work_id, person_id, role);
            """,
            reverse_sql='DROP INDEX film_work_person_idx;',
        ),
    ]
