# Generated by Django 4.2.11 on 2024-07-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_auto_20240710_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="creation_date",
            field=models.DateField(blank=True, null=True, verbose_name="creation date"),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("актер", "Actor"),
                    ("продюсер", "Producer"),
                    ("режиссер", "Director"),
                ],
                default="актер",
                verbose_name="role",
            ),
        ),
    ]
