# Generated by Django 4.2.11 on 2024-09-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_filmwork_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={'managed': False, 'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'managed': False, 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False, 'verbose_name': 'actor', 'verbose_name_plural': 'actors'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'managed': False},
        ),
    ]
