"""Initial migration

Revision ID: cef01d25d4d2
Revises: 
Create Date: 2024-07-30 20:46:06.712767

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cef01d25d4d2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "film",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("creation_date", sa.Date(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("modified", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="content",
    )
    op.create_table(
        "genre",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("modified", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="content",
    )
    op.create_table(
        "person",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("modified", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="content",
    )
    op.create_table(
        "genre_film",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("genre_id", sa.UUID(), nullable=False),
        sa.Column("film_id", sa.UUID(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["content.film.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["content.genre.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "film_id", "genre_id", name="unique_film_genre_role_idx"
        ),
        schema="content",
    )
    op.create_table(
        "person_film",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("film_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["content.film.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["content.person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "film_id", "person_id", "role", name="film_person_role_idx"
        ),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("person_film", schema="content")
    op.drop_table("genre_film", schema="content")
    op.drop_table("person", schema="content")
    op.drop_table("genre", schema="content")
    op.drop_table("film", schema="content")
    # ### end Alembic commands ###
